name: CBIG_BA
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cryptography=37.0.1
  - cudatoolkit=11.0.3
  - ffmpeg=4.3.2
  - freetype=2.11.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=1.1.1o
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=61.2.0
  - sqlite=3.38.2
  - tbb=2021.3.0
  - tk=8.6.11
  - typing_extensions=4.2.0
  - tzdata=2022a
  - urllib3=1.26.9
  - wheel=0.37.1
  - x264=1!161.3030
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - alembic==1.8.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - astunparse==1.6.3
    - attrs==21.4.0
    - autopage==0.5.1
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - bokeh==2.2.3
    - cachetools==5.2.0
    - click==8.1.3
    - cliff==3.10.1
    - cmaes==0.8.2
    - cmd2==2.4.2
    - colorlog==6.6.0
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - flatbuffers==23.5.26
    - fonttools==4.33.0
    - gast==0.4.0
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - greenlet==1.1.2
    - grpcio==1.56.0
    - h5py==3.7.0
    - humanize==4.2.0
    - importlib-metadata==5.0.0
    - ipykernel==6.13.0
    - ipython==8.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.0.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.2.2
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kaleido==0.2.1
    - keras==2.13.1
    - kiwisolver==1.4.2
    - libclang==14.0.6
    - lxml==4.8.0
    - mako==1.2.1
    - mapca==0.0.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mccabe==0.7.0
    - mistune==0.8.4
    - munkres==1.1.4
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - nibabel==3.2.2
    - nilearn==0.9.1
    - notebook==6.4.11
    - numpy==1.24.3
    - oauthlib==3.2.2
    - openpyxl==3.0.9
    - opt-einsum==3.3.0
    - optuna==2.10.1
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pbr==5.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.0
    - plotly==5.9.0
    - prettytable==3.3.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==4.23.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.0
    - pyflakes==2.5.0
    - pygments==2.11.2
    - pyparsing==3.0.8
    - pyperclip==1.8.2
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - send2trash==1.8.0
    - simpleitk==2.1.1.2
    - six==1.15.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.39
    - stack-data==0.2.0
    - stevedore==4.0.0
    - tedana==0.0.12
    - tenacity==8.0.1
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.13.0
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.28.0
    - termcolor==2.1.1
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - torch==1.7.1+cu110
    - torchinfo==1.7.1
    - torchio==0.18.79
    - torchsummary==1.5.1
    - torchvision==0.8.2+cu110
    - "-f https://download.pytorch.org/whl/torch_stable.html"
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==3.6.0
    - wrapt==1.12.1
    - yapf==0.32.0
    - zipp==3.9.0
